name: Virus Scan

on:
  push:
    branches:
      - main
      - virus_scan

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: virus-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:

  VirusScan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: "Build"
      run: make
      
    - name: "Git AV Scan"
      uses: djdefi/gitavscan@main
      with:
        full: '--full'
